modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/parmort/mc-icraftinpeace/issues"
displayURL="https://curseforge.com/minecraft/mc-mods/i-craft-in-peace"
logoFile="logo.png"
# credits=""
authors="parmort"

[[mods]]
    modId="icraftinpeace"
    version="${file.jarVersion}"
    displayName="I Craft in Peace"
    # updateJSONURL=""
    description='''
This is a mod that makes playing in peaceful mode (because you wimp out like me) possible.
The only purpose is to add crafting recipes and items purely to unlock otherwise unattainable items.
    '''

[[dependencies.icraftinpeace]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.icraftinpeace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
